spring:
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        connect-timeout: 5000
        database: 0
    thymeleaf:
        enabled: true
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/user
    session:
        store-type: redis
        timeout: 2m
        redis:
            flush-mode: on_save
            namespace: redis:session
server:
    servlet:
        context-path: /session
